services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        container_name: php
        volumes:
            - .:/var/www/html
        depends_on:
            - database
    web:
        build:
            context: .
            dockerfile: Dockerfile.apache
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
    database:
        image: mysql:8.0
        container_name: database
        volumes:
            - ./server_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: l@ravel_password
        ports:
            - "3306:3306"
        command:
            [
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--default-authentication-plugin=caching_sha2_password",
            ]
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - "8080:80"
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: root
